/*CREATE TABLE*/

CREATE TABLE CAN_CAMPAIGN(
CANDIDATE VARCHAR(12),
CAMPAIGN VARCHAR(12)
)


INSERT INTO can_campaign VALUES
('Carolyn','MNC'),
('Carolyn','YUI'),
('Melessa','MNC'),
('Melessa','YUI'),
('Melessa','MNC')


/*Write a Query to show all campaign in one row for each candidtes */

WITH CTE AS(
SELECT CANDIDATE,CAMPAIGN,LAG(CAMPAIGN,1) OVER(PARTITION BY CANDIDATE) AS IDEA
FROM(
SELECT DISTINCT *
FROM can_campaign)S)
SELECT CANDIDATE,CONCAT(CAMPAIGN,',',IDEA) AS CAMPAIGN FROM CTE
WHERE IDEA IS NOT NULL

/*PULL REQUEST AND SHARE YOUR CODE IN NEW BRANCH*/
-- FEEL FREE TO USE BUILT IN FUNCTION
HINT: STRING_AGG()